version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: nbd_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nbd_test_db
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=test
      - DATABASE_URL=postgresql://nbd_user:password@db:5432/nbd_test_db
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_USE_TLS=false
      - SMTP_USE_SSL=false
      - MAIL_FROM=alerts@nbd-wetland.org
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/your-service-account.json
      - GCS_BUCKET_NAME=your-gcs-bucket-name
      - KOBOTOOLBOX_API_URL=https://eu.kobotoolbox.org
      - KOBOTOOLBOX_API_TOKEN=your_actual_token_here
      - WHATSAPP_APP_SECRET=your_meta_app_secret_here
      - WHATSAPP_VERIFY_TOKEN=your_verify_token_here
      - WHATSAPP_ACCESS_TOKEN=your_whatsapp_access_token_here
      - WHATSAPP_PHONE_NUMBER_ID=your_phone_number_id_here
    command: ["./test.sh"]
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    command: ["./test.sh"]
