---
services:
  mainnetwork:
    ports:
      - "3000:80"    # Nginx Proxy
      - "5050:5050"  # PGAdmin 4
      - "1025:1025"  # Mailpit SMTP
      - "8025:8025"  # Mailpit Web UI


  pgadmin:
    network_mode: service:mainnetwork
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=dev@akvo.org
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - db

  backend:
    volumes:
      - ./backend:/app:delegated

  worker:
    volumes:
      - ./backend:/app:delegated

  frontend:
    volumes:
      - ./frontend:/app:delegated

volumes:
  pg-admin-data:
