version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: nbd_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nbd_test_db
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=test
      - DATABASE_URL=postgresql://nbd_user:password@db:5432/nbd_test_db
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_USE_TLS=false
      - SMTP_USE_SSL=false
      - MAIL_FROM=alerts@nbd-wetland.org
      - STORAGE_DIR=/app/storage_test
      - SECRET_KEY=your_test_secret_key_here
      - GOOGLE_CLIENT_ID=your_test_google_client_id_here
      - JWT_SECRET=your_test_secret_key_here
      - JWT_EXPIRY_HOURS=24
      - KOBOTOOLBOX_API_URL=https://eu.kobotoolbox.org
      - KOBOTOOLBOX_API_TOKEN=your_actual_token_here
      - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - TWILIO_AUTH_TOKEN=your_twilio_auth_token_here
      - TWILIO_NUMBER=whatsapp:+14155238886
    volumes:
      - ./backend:/app:delegated
      - ./storage_test:/app/storage_test
    command: ["./test.sh"]
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=your_test_google_client_id_here
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    command: ["./test.sh"]
