"""create_remaining_schemas

Revision ID: 384a4835396a
Revises: 888e48d777ff
Create Date: 2026-06-04 23:47:54.790332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "384a4835396a"
down_revision: Union[str, None] = "888e48d777ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fgd_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wetland_id", sa.UUID(), nullable=False),
        sa.Column("fish_abundance", sa.String(length=15), nullable=False),
        sa.Column("water_clarity", sa.String(length=15), nullable=False),
        sa.Column("vegetation_cover", sa.String(length=15), nullable=False),
        sa.Column("conducted_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "fish_abundance IN ('Same', 'Slight', 'Moderate', 'Severe')",
            name="check_fgd_records_fish_abundance",
        ),
        sa.CheckConstraint(
            "vegetation_cover IN ('Same', 'Partial Loss', 'Severe Loss')",
            name="check_fgd_records_vegetation_cover",
        ),
        sa.CheckConstraint(
            "water_clarity IN ('Same', 'Somewhat Worse', 'Much Worse')",
            name="check_fgd_records_water_clarity",
        ),
        sa.ForeignKeyConstraint(
            ["wetland_id"], ["wetlands.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_fgd_records_wetland",
        "fgd_records",
        ["wetland_id", sa.text("conducted_at DESC")],
        unique=False,
    )
    op.create_table(
        "citizens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(length=50), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "role IN ('WATCHER', 'SCIENTIST')", name="check_citizens_role"
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column(
            "wqi_score", sa.Numeric(precision=3, scale=2), nullable=False
        ),
        sa.Column(
            "composite_score", sa.Numeric(precision=3, scale=2), nullable=False
        ),
        sa.Column(
            "ik_signal_value", sa.Numeric(precision=3, scale=2), nullable=False
        ),
        sa.Column(
            "adjusted_score", sa.Numeric(precision=3, scale=2), nullable=False
        ),
        sa.Column("health_class", sa.String(length=1), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "health_class IN ('A', 'B', 'C', 'D', 'E')",
            name="check_health_scores_health_class",
        ),
        sa.CheckConstraint(
            "adjusted_score BETWEEN 0.00 AND 1.00",
            name="check_health_scores_adjusted_score",
        ),
        sa.CheckConstraint(
            "composite_score BETWEEN 0.00 AND 1.00",
            name="check_health_scores_composite_score",
        ),
        sa.CheckConstraint(
            "ik_signal_value BETWEEN 0.00 AND 1.00",
            name="check_health_scores_ik_signal_value",
        ),
        sa.CheckConstraint(
            "wqi_score BETWEEN 0.00 AND 1.00",
            name="check_health_scores_wqi_score",
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_health_scores_site",
        "health_scores",
        ["site_id", sa.text("calculated_at DESC")],
        unique=False,
    )
    op.create_table(
        "management_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("status_color", sa.String(length=10), nullable=False),
        sa.Column("short_label", sa.String(length=50), nullable=False),
        sa.Column("description_text", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status_color IN ('GREEN', 'YELLOW', 'RED')",
            name="check_management_actions_status_color",
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_management_actions_site_color",
        "management_actions",
        ["site_id", "status_color"],
        unique=False,
    )
    op.create_table(
        "sampling_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column(
            "ph_value", sa.Numeric(precision=4, scale=2), nullable=False
        ),
        sa.Column(
            "temp_value", sa.Numeric(precision=4, scale=1), nullable=False
        ),
        sa.Column(
            "do_value", sa.Numeric(precision=4, scale=1), nullable=False
        ),
        sa.Column(
            "invasive_macrophytes",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "cpue_value", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("water_level", sa.String(length=10), nullable=False),
        sa.Column("sampled_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "water_level IN ('HIGH', 'MEDIUM', 'LOW')",
            name="check_sampling_records_water_level",
        ),
        sa.CheckConstraint(
            "do_value BETWEEN 0.5 AND 35.0",
            name="check_sampling_records_do_value",
        ),
        sa.CheckConstraint(
            "invasive_macrophytes BETWEEN 0.0 AND 100.0",
            name="check_sampling_records_invasive_macrophytes",
        ),
        sa.CheckConstraint(
            "ph_value BETWEEN 2.0 AND 10.0",
            name="check_sampling_records_ph_value",
        ),
        sa.CheckConstraint(
            "temp_value BETWEEN 5.0 AND 50.0",
            name="check_sampling_records_temp_value",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sampling_records_site_date",
        "sampling_records",
        ["site_id", sa.text("sampled_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_sampling_records_site_date", table_name="sampling_records"
    )
    op.drop_table("sampling_records")
    op.drop_index(
        "idx_management_actions_site_color", table_name="management_actions"
    )
    op.drop_table("management_actions")
    op.drop_index("idx_health_scores_site", table_name="health_scores")
    op.drop_table("health_scores")
    op.drop_table("citizens")
    op.drop_index("idx_fgd_records_wetland", table_name="fgd_records")
    op.drop_table("fgd_records")
    # ### end Alembic commands ###
