"""create_form_blueprint

Revision ID: 8f4a19187b72
Revises: 9bd4883bba50
Create Date: 2026-06-04 03:31:51.419464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8f4a19187b72"
down_revision: Union[str, None] = "9bd4883bba50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("previous_version_id", sa.Integer(), nullable=True),
        sa.Column("active_version_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["form.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"], ["form.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_form_id"), "form", ["id"], unique=False)
    op.create_table(
        "form_published_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("published_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["form_id"], ["form.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_form_published_version_id"),
        "form_published_version",
        ["id"],
        unique=False,
    )
    op.create_index(
        "unique_form_published_version",
        "form_published_version",
        ["form_id", "version"],
        unique=True,
    )

    # Add cyclic foreign key constraint to form after
    # form_published_version table exists
    op.create_foreign_key(
        "form_active_version_id_fkey",
        "form",
        "form_published_version",
        ["active_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "question_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("order", sa.BigInteger(), nullable=True),
        sa.Column("repeatable", sa.Boolean(), nullable=False),
        sa.Column("repeat_text", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["form_id"], ["form.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_group_id"), "question_group", ["id"], unique=False
    )
    op.create_index(
        "unique_active_form_question_group",
        "question_group",
        ["form_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("question_group_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.BigInteger(), nullable=True),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("short_label", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "input",
                "number",
                "cascade",
                "text",
                "date",
                "option",
                "multiple_option",
                "tree",
                "table",
                "autofield",
                "image",
                "geo",
                "geotrace",
                "geoshape",
                "entity",
                "signature",
                "attachment",
                name="question_type",
            ),
            nullable=False,
        ),
        sa.Column("meta", sa.Boolean(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "rule", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "dependency",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("dependency_rule", sa.String(length=3), nullable=True),
        sa.Column(
            "api", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "tooltip", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "fn", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "pre", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("display_only", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["form_id"], ["form.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["question_group_id"], ["question_group.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_question_id"), "question", ["id"], unique=False)
    op.create_index(
        "unique_active_form_question",
        "question",
        ["form_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "option",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.BigInteger(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("value", sa.String(length=255), nullable=True),
        sa.Column("other", sa.Boolean(), nullable=False),
        sa.Column("color", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_option_id"), "option", ["id"], unique=False)
    op.create_index(
        "unique_question_option",
        "option",
        ["question_id", "value"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "form_active_version_id_fkey", "form", type_="foreignkey"
    )
    op.drop_index("unique_question_option", table_name="option")
    op.drop_index(op.f("ix_option_id"), table_name="option")
    op.drop_table("option")
    op.drop_index(
        "unique_active_form_question",
        table_name="question",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_question_id"), table_name="question")
    op.drop_table("question")
    op.drop_index(
        "unique_active_form_question_group",
        table_name="question_group",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_question_group_id"), table_name="question_group")
    op.drop_table("question_group")
    op.drop_index(
        "unique_form_published_version", table_name="form_published_version"
    )
    op.drop_index(
        op.f("ix_form_published_version_id"),
        table_name="form_published_version",
    )
    op.drop_table("form_published_version")
    op.drop_index(op.f("ix_form_id"), table_name="form")
    op.drop_table("form")
    sa.Enum(name="question_type").drop(op.get_bind(), checkfirst=True)
