"""create whatsapp_sessions table

Revision ID: 31a98d3049de
Revises: c7a8c7dad9eb
Create Date: 2026-06-08 00:11:35.337411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31a98d3049de"
down_revision: Union[str, None] = "c7a8c7dad9eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatsapp_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "phone_number",
            sa.String(length=20),
            nullable=False,
            comment="E.164 formatted number",
        ),
        sa.Column(
            "state",
            sa.String(length=30),
            nullable=False,
            comment="Current conversation state",
        ),
        sa.Column(
            "incident_type",
            sa.String(length=50),
            nullable=True,
            comment="Selected incident category code",
        ),
        sa.Column(
            "option_text",
            sa.Text(),
            nullable=True,
            comment="Human readable option text selected by user",
        ),
        sa.Column(
            "media_url",
            sa.String(length=255),
            nullable=True,
            comment="Temporary Meta media URL (expires rapidly)",
        ),
        sa.Column(
            "location",
            sa.String(length=255),
            nullable=True,
            comment="User provided location identifier or coordinates",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_whatsapp_sessions_id"),
        "whatsapp_sessions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_sessions_phone_number"),
        "whatsapp_sessions",
        ["phone_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f("ix_whatsapp_sessions_phone_number"),
        table_name="whatsapp_sessions",
    )
    op.drop_index(
        op.f("ix_whatsapp_sessions_id"), table_name="whatsapp_sessions"
    )
    op.drop_table("whatsapp_sessions")
    # ### end Alembic commands ###
