"""create_dead_letters_table

Revision ID: 60bb12386be3
Revises: 9a2d401e1ffd
Create Date: 2026-06-04 05:39:38.081634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "60bb12386be3"
down_revision: Union[str, None] = "9a2d401e1ffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dead_letters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.String(length=50), nullable=False),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("error_reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_dead_letters_status_source",
        "dead_letters",
        ["status", "source_system"],
        unique=False,
    )
    op.drop_constraint("sites_wetland_id_fkey", "sites", type_="foreignkey")
    op.create_foreign_key(
        None,
        "sites",
        "wetlands",
        ["wetland_id"],
        ["wetland_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "wetlands_basin_id_fkey", "wetlands", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "wetlands",
        "basins",
        ["basin_id"],
        ["basin_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "wetlands_basin_id_fkey", "wetlands", type_="foreignkey"
    )
    op.create_foreign_key(
        "wetlands_basin_id_fkey",
        "wetlands",
        "basins",
        ["basin_id"],
        ["basin_id"],
    )
    op.drop_constraint("sites_wetland_id_fkey", "sites", type_="foreignkey")
    op.create_foreign_key(
        "sites_wetland_id_fkey",
        "sites",
        "wetlands",
        ["wetland_id"],
        ["wetland_id"],
    )
    op.drop_index("idx_dead_letters_status_source", table_name="dead_letters")
    op.drop_table("dead_letters")
    # ### end Alembic commands ###
