"""create_submission_tables

Revision ID: 9a2d401e1ffd
Revises: 91f3ab6baa62
Create Date: 2026-06-04 04:19:06.215650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a2d401e1ffd"
down_revision: Union[str, None] = "91f3ab6baa62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datapoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("published_version_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("basin_id", sa.String(length=50), nullable=True),
        sa.Column("wetland_id", sa.String(length=50), nullable=True),
        sa.Column("site_id", sa.String(length=50), nullable=True),
        sa.Column(
            "geo", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("submitter", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "(basin_id IS NOT NULL)::int + (wetland_id IS NOT NULL)::int + (site_id IS NOT NULL)::int = 1",
            name="chk_polymorphic_anchor",
        ),
        sa.ForeignKeyConstraint(
            ["basin_id"], ["basins.basin_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["form_id"], ["form.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["published_version_id"],
            ["form_published_version.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.site_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["wetland_id"], ["wetlands.wetland_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_datapoint_id"), "datapoint", ["id"], unique=False)
    op.create_table(
        "answer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datapoint_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column(
            "options", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["datapoint_id"], ["datapoint.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "datapoint_id",
            "question_id",
            "index",
            name="unique_datapoint_question_index",
        ),
    )
    op.create_index(op.f("ix_answer_id"), "answer", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_answer_id"), table_name="answer")
    op.drop_table("answer")
    op.drop_index(op.f("ix_datapoint_id"), table_name="datapoint")
    op.drop_table("datapoint")
    # ### end Alembic commands ###
