"""create_spatial_hierarchy

Revision ID: 9bd4883bba50
Revises:
Create Date: 2026-06-04 01:08:52.885110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "9bd4883bba50"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "basins",
        sa.Column("basin_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("basin_id"),
    )
    #
    op.create_table(
        "wetlands",
        sa.Column("wetland_id", sa.String(length=50), nullable=False),
        sa.Column("basin_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["basin_id"],
            ["basins.basin_id"],
        ),
        sa.PrimaryKeyConstraint("wetland_id"),
    )
    #
    op.create_table(
        "sites",
        sa.Column("site_id", sa.String(length=50), nullable=False),
        sa.Column("wetland_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["wetland_id"],
            ["wetlands.wetland_id"],
        ),
        sa.PrimaryKeyConstraint("site_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("sites")
    op.drop_table("wetlands")
    op.drop_table("basins")
    # ### end Alembic commands ###
