"""create_reconciliation_log

Revision ID: df362444cf35
Revises: 7a8b417c8d9e
Create Date: 2026-06-15 13:25:18.521749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df362444cf35"
down_revision: Union[str, None] = "7a8b417c8d9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliation_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("citizen_id", sa.UUID(), nullable=False),
        sa.Column("citizen_datapoint_id", sa.UUID(), nullable=False),
        sa.Column("lab_datapoint_id", sa.Integer(), nullable=False),
        sa.Column("parameter_name", sa.String(length=50), nullable=False),
        sa.Column(
            "citizen_value", sa.Numeric(precision=6, scale=2), nullable=False
        ),
        sa.Column(
            "lab_value", sa.Numeric(precision=6, scale=2), nullable=False
        ),
        sa.Column(
            "calculated_variance",
            sa.Numeric(precision=6, scale=2),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reconciled_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["citizen_datapoint_id"],
            ["sampling_records.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["citizen_id"], ["citizens.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lab_datapoint_id"], ["datapoint.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "citizen_id",
            "citizen_datapoint_id",
            "lab_datapoint_id",
            "parameter_name",
            name="uq_reconciliation_log_pair",
        ),
    )
    op.create_index(
        "idx_reconciliation_log_citizen_id",
        "reconciliation_log",
        ["citizen_id"],
        unique=False,
    )
    op.create_index(
        "idx_reconciliation_log_status",
        "reconciliation_log",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_reconciliation_log_status", table_name="reconciliation_log"
    )
    op.drop_index(
        "idx_reconciliation_log_citizen_id", table_name="reconciliation_log"
    )
    op.drop_table("reconciliation_log")
    # ### end Alembic commands ###
